### ISSUE TITLE
Binder won't build

### ISSUE THREAD

**Issue by rabernat** [OpenGeoVis/PVGeo-Examples#1]
I just tried launching this binder. The build failed with the error

```
Step 41/55 : RUN ${KERNEL_PYTHON_PREFIX}/bin/pip install --no-cache-dir -r "requirements.txt"
 ---> [Warning] Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
 ---> Running in b09f0cdc7df7
Collecting git+git://github.com/OpenGeoVis/PVGeo@master (from -r requirements.txt (line 3))
  Cloning git://github.com/OpenGeoVis/PVGeo (to revision master) to /tmp/pip-req-build-uvatm4wb
  Running command git clone -q git://github.com/OpenGeoVis/PVGeo /tmp/pip-req-build-uvatm4wb
ERROR: Could not find a version that satisfies the requirement vista>=0.19.0
ERROR: No matching distribution found for vista>=0.19.0
```

**Comment by banesullivan** [comment]
Huh. I'll get on this

**Comment by banesullivan** [comment]
FYI, these notebooks are quite old. I'd recommend the examples in PVGeo's docs over these but I will do what I can to get these up and running again.

**Comment by banesullivan** [comment]
Actually. these are so outdated I am going to archive this repo and move what I can into PVGeo's examples gallery

**Comment by banesullivan** [comment]
the content of these notebooks mostly exist elsewhere now:

- `1.0 - Welcome.ipynb`
  - https://pvgeo.org/overview/getting-started.html
  - https://pvgeo.org/overview/agu-2018.html
  - Points to Voxelized Volume: https://pvgeo.org/examples/filters-general/voxelize-points.html
  - Slice Volumetric Data: https://docs.pyvista.org/examples/01-filter/slicing.html
  - Integrated Visualization: any example with more than one mesh in PyVista or PVGeo's doc
- `1.1 - Using the vista Package.ipynb`
  - Generally, see PyVista's docs.
  - The specific example with Craig's data is here: 
- `2.0 - PVGeo+Discretize.ipynb`
  - Follow this: http://discretize.simpeg.xyz/en/master/examples/plot_pyvista_laguna.html
- `2.1 - Loading-Shapefiles-To-VTK.ipynb`
  - This is the only one that does not exist in the docs anywhere. There are better ways to go about this. So someone will have to open an issue over in the PyVista support forum for demoing loading shapefiles
- `2.2 - omfvtk.ipynb`
  - See https://opengeovis.github.io/omfvista/index.html
